apiVersion: v1
kind: Secret
metadata:
  name: yarismasecret
type: Opaque
stringData:
  db_username: 'postgres'
  db_password: 'Hande0808'
  db_url: 'jdbc:postgresql://10.4.1.10:5432/YarismaDB'
  services_auth_clusterip: '10.8.2.15'
  services_main_clusterip: '10.8.3.104'
  services_user_clusterip: '10.8.4.90'
  auth_port: '9090'
  main_port: '9091'
  user_port: '9092'
  auth_url: 'http://10.8.2.15:9090/'
  main_url: 'http://10.8.3.104:9091/'
  user_url: 'http://10.8.4.90:9092/'
  gateway_auth_url: 'http://10.8.2.15:9090'
  gateway_main_url: 'http://10.8.3.104:9091'
  gateway_user_url: 'http://10.8.4.90:9092'
  config_server_url: 'http://10.4.1.11:8888'
  