server:
  port: 9092


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YarismaMainDB
    username: postgres
    password: Hande0808
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true